extraction:
  cpp:
    prepare:
      packages:
        - libtclap-dev
        - libgnutls28-dev
        - libgnutlsxx28
        - uuid-dev
        - libncurses5-dev
        - libnotify-dev
        - libuv1-dev
        - libcurl4-gnutls-dev
        - build-essential
        - gcc-9
        - g++-9
    after_prepare:
      - export PATH="${HOME}/dependencies/install/bin:$PATH"
      - export PKG_CONFIG_PATH="${HOME}/dependencies/install/lib/pkgconfig"
      - export CC="gcc-9"
      - export CXX="g++-9"
      - PCONFIGURE_VERSION=0.12.5
      - PSQLITE_VERSION=0.0.7
      - PUTIL_VERSION=0.0.6
      - LIBBASE64_VERSION=1.0.0_p3
      - GITDATE_VERSION=0.0.3
      - PSON_VERSION=0.0.4
      - export MAKEFLAGS="-j3"
      - export S="$(pwd)"
      - mkdir -p "${HOME}/dependencies"
      - cd "${HOME}/dependencies"
      - wget "https://github.com/palmer-dabbelt/pconfigure/archive/v${PCONFIGURE_VERSION}.tar.gz" -O "${PCONFIGURE_VERSION}.tar.gz"
      - tar -xvzpf "${PCONFIGURE_VERSION}.tar.gz"
      - cd "pconfigure-${PCONFIGURE_VERSION}"
      - ./bootstrap.sh --prefix "${HOME}/dependencies/install"
      - make install
      - cd "${HOME}/dependencies"
      - wget "https://github.com/palmer-dabbelt/gitdate/archive/v${GITDATE_VERSION}.tar.gz" -O "${GITDATE_VERSION}.tar.gz"
      - tar -xvzpf "${GITDATE_VERSION}.tar.gz"
      - cd "gitdate-${GITDATE_VERSION}"
      - pconfigure --verbose "PREFIX = ${HOME}/dependencies/install"
      - make
      - make install
      - cd "${HOME}/dependencies"
      - wget "https://github.com/palmer-dabbelt/psqlite/archive/v${PSQLITE_VERSION}.tar.gz" -O "${PSQLITE_VERSION}.tar.gz"
      - tar -xvzpf "${PSQLITE_VERSION}.tar.gz"
      - cd "psqlite-${PSQLITE_VERSION}"
      - pconfigure --verbose "PREFIX = ${HOME}/dependencies/install"
      - make install
      - cd "${HOME}/dependencies"
      - wget "https://github.com/palmer-dabbelt/putil/archive/v${PUTIL_VERSION}.tar.gz" -O "${PUTIL_VERSION}.tar.gz"
      - tar -xvzpf "${PUTIL_VERSION}.tar.gz"
      - cd "putil-${PUTIL_VERSION}"
      - pconfigure --verbose "PREFIX = ${HOME}/dependencies/install"
      - make install
      - cd "${HOME}/dependencies"
      - wget "https://github.com/palmer-dabbelt/libbase64/archive/v${LIBBASE64_VERSION}.tar.gz" -O "${LIBBASE64_VERSION}.tar.gz"
      - tar -xvzpf "${LIBBASE64_VERSION}.tar.gz"
      - cd "libbase64-${LIBBASE64_VERSION}"
      - autoreconf -i
      - ./configure --prefix="${HOME}/dependencies/install"
      - make
      - make install
      - cd "${HOME}/dependencies"
      - wget "https://github.com/palmer-dabbelt/pson/archive/v${PSON_VERSION}.tar.gz" -O "${PSON_VERSION}.tar.gz"
      - tar -xvzpf "${PSON_VERSION}.tar.gz"
      - cd "pson-${PSON_VERSION}"
      - pconfigure --verbose "PREFIX = ${HOME}/dependencies/install"
      - make install
      - cd "${S}"
    configure:
      command:
        - pconfigure --verbose
    index:
      build_command:
        - make
